### ISSUE TITLE
Corrupt Data Packet on ETC

### ISSUE THREAD

**Issue by citrusbits** [ElectronicTheatreControlsLabs/EosSyncDemo#1]
Hi 
I am using this library for iPad application. Its working fine with iPad 2,3,4 but on iPad AIR it is saving corrupt data packet. Also What is the Purpose of Swap64 method in this library and how to use that in order to send and receive data.

**Comment by MizPlusPlus** [comment]
Hello,

Happy to help!  Could you please expand a little more about the problem you are running into?  Maybe have you have specific example I could try and reproduce?  Based on the information here (and your questions) I assume this could be related to processor differences between the various iPad models.  Differences between a 32-bit and 64-bit OS could have an impact on this code, as well as differences in endianness.  The Swap64 function is used to swap endianness of data in the network packets, specifically 64-bit primitives, like int64_t, uint64_t, and double.

~Chris
